// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_publish from "./routes/api/publish.ts";
import * as $index from "./routes/index.tsx";
import * as $r from "./routes/r.ts";
import * as $ClippyEditor from "./islands/ClippyEditor.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/publish.ts": $api_publish,
    "./routes/index.tsx": $index,
    "./routes/r.ts": $r,
  },
  islands: {
    "./islands/ClippyEditor.tsx": $ClippyEditor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
